### ISSUE TITLE
統合開発環境の選定

### ISSUE THREAD

**Issue by ktanaka0821** [igarashi339/chat-room#1]
ruby on railsで開発する上で、無料で使用できる統合開発環境を見つける必要がある。  
  
現状、AWS Cloud9を利用することで、気軽に利用することができる。  
ネットワークがない場合、また無料期間が決まっている等のデメリットがあるため、ローカルで実行できる統合開発環境を探す必要がある。  
  
## 選択肢  
* Eclips
* Visual Studio Code (今のところ一番良さそう)

**Comment by ktanaka0821** [comment]
IntelliJを利用しようとしたが、ruby on railsのプラグインを入れる際に有料でなければ取得できないことが判明し、IntelliJの利用を断念。

**Comment by ktanaka0821** [comment]
Ruby Mineは有償のため選択外

**Comment by ktanaka0821** [comment]
Mac、VSCodeの相性が抜群に良く、とても使いやすい。  
セットアップ方法もネットに情報が多いので比較的使用率はメジャーになりつつあるのか。

**Comment by igarashi339** [comment]
開発環境決まったみたいだし、このissue閉じちゃっていいですかね？
