### ISSUE TITLE
フロントフレームワークが実装されていない

### ISSUE THREAD

**Issue by ktanaka0821** [igarashi339/chat-room#10]
フロント開発をするに当たって、開発の品質を高め、スピードを早めるためにフロントフレームワークを実装する必要がある。  
また、フロントフレームワークを後々採用することによるデメリットとして、既にあるcss(bootstrap)の記述、javascriptの記述に固執、または移植する必要が出てくる。そのため、早期段階で採用を決定する。  

又、railsベースでフロント開発を進めると言語（Coffee Script）、Sprockets（アセットパイプライン）に依存するため、javascript、cssのリソース管理がgemになってしまう。  
切り分けやライブラリの豊富さを選択するためにも、フロントフレームワークを採用し、npm等によるフロント側専用のパッケージ管理を行いたい。

- React  
中規模〜大規模に対して向いており、ユーザーインタフェースの向上を目的に使用する。  
学習コストも低く、文書等のコミュニティが活発のため、人気が高い。

- Vue
小規模〜中規模に対して向いており、ユーザーインタフェースの向上を目的に使用する。  
学習コストはメジャーどころでは一番低く、歴史は短いがコミュニティが活発。日本語の記事が少ない

- Angular  
大規模に対して向いており、フルスタックを目的に使用する。  
学習コストは高く、文書等も多い。ルーティング等のもフルスタックのため用意されているため、これ1つで完結することができる。

**Comment by ktanaka0821** [comment]
現状、今の開発目的から見るとReact, Vueが向いている。  
個人的にはReactのロゴがかっこいいからこれにしようと思っている

**Comment by ktanaka0821** [comment]
Reactrのコンポーネントセットはmaterial-uiを使用し、今使用しているbootstrapを除去しようと考えている。

**Comment by igarashi339** [comment]
Reactでやることに決定ためクローズ。
