### ISSUE TITLE
WebApplicationのデプロイ環境の構築

### ISSUE THREAD

**Issue by ktanaka0821** [igarashi339/chat-room#11]
本番用として開発第一弾のチャットWebApplicationをデプロイする環境を用意する必要がある。  

テスト（開発）用の環境も本来では用意する必要があるが、コスト的に考えて無くていいかな。

**Comment by igarashi339** [comment]
https://github.com/igarashi339/chat-room/pull/13
にて、本番環境にデプロイが完了したためクローズとする。
