### ISSUE TITLE
URL指定でアクセスするとNginxのデフォルトページに遷移してしまう

### ISSUE THREAD

**Issue by igarashi339** [igarashi339/chat-room#12]
IPアドレスからアクセスするとアプリ起動画面に遷移できるが、ホスト名を指定してアクセスするとNginxのデフォルトページに遷移してしまうという不具合が発生している。

パブリックDNS：http://ec2-3-223-183-197.compute-1.amazonaws.com 
IPアドレス：http://3.223.183.197/ 

原因を特定し、ホスト名指定でアクセスできるよう修正を行う。

**Comment by igarashi339** [comment]
参考になりそうなサイト
https://teratail.com/questions/107039
https://pig-log.com/nginx-virtual-host/

**Comment by ktanaka0821** [comment]
closeします
